# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-04 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('startdate', models.DateField(verbose_name='%d/%m/%Y')),
                ('mat_date', models.DateField(verbose_name='%d/%m/%Y')),
                ('amount', models.FloatField()),
            ],
        ),
    ]
